version: '3'

services:
        #judgehost可以依需要多設幾個，名字、hostname、DAEMON_ID記得改
        dj-judgehost_1:
                image: domjudge/judgehost:latest
                privileged: true
                hostname: judgedaemon-0
                volumes:
                        - /sys/fs/cgroup:/sys/fs/cgroup:ro
                #environment:
                        #- CONTAINER_TIMEZONE=Europe/Belfast
                        #- DAEMON_ID=0
                        #DOMSERVER_BASEURL可以指定domserver的IP，從而在另一個終端開judgehost
                        #- DOMSERVER_BASEURL=127.0.0.1
                links:
                        - dj-domserver:domserver
                env_file:
                        - judgehost.env

        dj-judgehost_2:
                image: domjudge/judgehost:latest
                privileged: true
                hostname: judgedaemon-1
                volumes:
                        - /sys/fs/cgroup:/sys/fs/cgroup:ro
                #environment:
                        #- CONTAINER_TIMEZONE=Europe/Belfast
                        #- DAEMON_ID=1
                links:
                        - dj-domserver:domserver
                env_file:
                        - judgehost.env
